[workspace]
members = ["zorua_macro"]

[package]
name = "zorua"
version = "0.3.0"
edition = "2021"

[dependencies]
paste = "1.0.14"
aligned = "0.4.1"
ux2 = "0.8.5"
zorua_macro = { path = "zorua_macro" }
